//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackMyBets.Business.Exceptions {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrackMyBets.Business.Exceptions.Descriptions", typeof(Descriptions).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one Bookmaker with these name ({0})..
        /// </summary>
        internal static string DuplicateBookmaker {
            get {
                return ResourceManager.GetString("DuplicateBookmaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one Event with these data ({0})..
        /// </summary>
        internal static string DuplicateEvent {
            get {
                return ResourceManager.GetString("DuplicateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one RelUserBookmaker with these user and bookmaker ({0})..
        /// </summary>
        internal static string DuplicateRelUserBookmaker {
            get {
                return ResourceManager.GetString("DuplicateRelUserBookmaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one Sport with these name ({0})..
        /// </summary>
        internal static string DuplicateSport {
            get {
                return ResourceManager.GetString("DuplicateSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one Team with these name ({0})..
        /// </summary>
        internal static string DuplicateTeam {
            get {
                return ResourceManager.GetString("DuplicateTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one User with these nick ({0})..
        /// </summary>
        internal static string DuplicateUser {
            get {
                return ResourceManager.GetString("DuplicateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found Bookmaker with these id ({0})..
        /// </summary>
        internal static string NotFoundBookmaker {
            get {
                return ResourceManager.GetString("NotFoundBookmaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found Event with these id ({0})..
        /// </summary>
        internal static string NotFoundEvent {
            get {
                return ResourceManager.GetString("NotFoundEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found Pick with these id ({0})..
        /// </summary>
        internal static string NotFoundPick {
            get {
                return ResourceManager.GetString("NotFoundPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found RelUserBookmaker with these id ({0})..
        /// </summary>
        internal static string NotFoundRelUserBookmaker {
            get {
                return ResourceManager.GetString("NotFoundRelUserBookmaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found Sport with these id ({0})..
        /// </summary>
        internal static string NotFoundSport {
            get {
                return ResourceManager.GetString("NotFoundSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found Team with these id ({0})..
        /// </summary>
        internal static string NotFoundTeam {
            get {
                return ResourceManager.GetString("NotFoundTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found User with these id ({0})..
        /// </summary>
        internal static string NotFoundUser {
            get {
                return ResourceManager.GetString("NotFoundUser", resourceCulture);
            }
        }
    }
}
